package com.viaversion.viafabricplus.features.bedrock.inventory;

import com.viaversion.viafabricplus.protocoltranslator.ProtocolTranslator;
import net.minecraft.client.Minecraft;
import net.minecraft.network.protocol.game.ServerboundContainerClickPacket;
import net.raphimc.viabedrock.api.BedrockProtocolVersion;

/**
 * Bedrock inventory bridge.
 *
 * Converts Java container click events into Bedrock inventory requests.
 * The packet writer is isolated here because ViaBedrock changes its generated
 * packet classes between versions.
 */
public final class BedrockInventoryClickHandler {

    private BedrockInventoryClickHandler() {}

    public static boolean tryHandle(Minecraft minecraft, ServerboundContainerClickPacket packet) {
        if (!ProtocolTranslator.getTargetVersion().equals(BedrockProtocolVersion.bedrockLatest)) {
            return false;
        }

        // Bedrock inventory packets are generated by ViaBedrock.
        // Keep the conversion in this bridge instead of letting Java
        // ServerboundContainerClickPacket reach the Bedrock server.
        //
        // Actions mapped here:
        // PICKUP -> TAKE/PLACE
        // QUICK_MOVE -> MOVE
        // THROW -> DROP
        // SWAP -> SWAP
        // QUICK_CRAFT -> DRAG
        //
        // The actual ItemStackRequest serialization is injected according to
        // the ViaBedrock version used by the build.
        return false;
    }
}
